server:
  port: 8888

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/tresende/spring-cloud-micro-services
          search-paths: microservice-repo