
server:
  port: 5555

spring:
  application:
    name: 'gateway-service'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "routes"

ribbon:
  ReadTimeout: 5000
